from maze_solver.maze_solver import RandomWalkerMazeSolver
from maze_solver.maze_solving_session import SimulatorMazeSolvingSession
from maze_solver.maze import MazeSquare, Maze

def create_simple_2_to_2_maze() -> Maze:
    _squares = [
        MazeSquare(x = 1, y = 1, x_plus = True, y_plus = True, is_start = True),
        MazeSquare(x = 1, y = 2, y_minus = True),
        MazeSquare(x = 2, y = 1, y_plus = True, x_minus = True),
        MazeSquare(x = 2, y = 2, y_minus = True, is_finish = True)
    ]
    return Maze(_squares)

def create_simple_3_to_3_maze() -> Maze:
    _squares = [
        MazeSquare(x = 1, y = 1, x_plus = True, is_start = True),
        MazeSquare(x = 1, y = 2, y_plus = True),
        MazeSquare(x = 1, y = 3, x_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 1, y_plus = True, x_minus = True),
        MazeSquare(x = 2, y = 2, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 3, x_minus = True, y_minus = True),
        MazeSquare(x = 3, y = 1, y_plus = True),
        MazeSquare(x = 3, y = 2, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 3, y = 3, y_minus = True, is_finish = True)
    ]
    return Maze(_squares)

def create_6_to_6_maze() -> Maze:
    _squares = [
        MazeSquare(x = 1, y = 1, x_plus = True, is_start = True),
        MazeSquare(x = 1, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 3, x_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 4, x_plus = True),
        MazeSquare(x = 1, y = 5, y_plus = True),
        MazeSquare(x = 1, y = 6, x_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 1, x_plus = True, y_plus = True),
        MazeSquare(x = 2, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 3, x_minus = True, y_minus = True),
        MazeSquare(x = 2, y = 4, x_plus = True, y_plus = True, x_minus = True),
        MazeSquare(x = 2, y = 5, y_minus = True),
        MazeSquare(x = 2, y = 6, x_plus = True, x_minus = True),
        MazeSquare(x = 3, y = 1, x_plus = True, x_minus = True),
        MazeSquare(x = 3, y = 2, x_plus = True, y_plus = True),
        MazeSquare(x = 3, y = 3, y_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 4, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 3, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 6, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 4, y = 1, y_plus = True, x_minus = True),
        MazeSquare(x = 4, y = 2, x_minus = True, y_minus = True),
        MazeSquare(x = 4, y = 3, x_plus = True, y_plus = True),
        MazeSquare(x = 4, y = 4, y_minus = True, is_finish = True),
        MazeSquare(x = 4, y = 5, y_plus = True),
        MazeSquare(x = 4, y = 6, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 5, y = 1, y_plus = True),
        MazeSquare(x = 5, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 5, y = 3, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 5, y = 4, x_plus = True, y_plus = True),
        MazeSquare(x = 5, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 5, y = 6, x_minus = True, y_minus = True),
        MazeSquare(x = 6, y = 1, y_plus = True),
        MazeSquare(x = 6, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 3, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 6, y = 4, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 6, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 6, y_minus = True),
    ]
    return Maze(_squares)

def create_a_real_16_to_16_beast() -> Maze:
    _squares = [
        MazeSquare(x = 1, y = 1, y_plus = True, is_start = True),
        MazeSquare(x = 1, y = 2, x_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 3, x_plus = True),
        MazeSquare(x = 1, y = 4, x_plus = True, y_plus = True),
        MazeSquare(x = 1, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 6, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 7, x_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 8, x_plus = True, y_plus = True),
        MazeSquare(x = 1, y = 9, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 10, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 11, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 12, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 13, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 14, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 15, y_plus = True, y_minus = True),
        MazeSquare(x = 1, y = 16, x_plus = True, y_minus = True),

        MazeSquare(x = 2, y = 1, x_plus = True, y_plus = True),
        MazeSquare(x = 2, y = 2, x_minus = True, y_minus = True),
        MazeSquare(x = 2, y = 3, x_plus = True, x_minus = True),
        MazeSquare(x = 2, y = 4, x_plus = True, y_plus = True, x_minus = True),
        MazeSquare(x = 2, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 6, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 7, x_minus = True, y_minus = True),
        MazeSquare(x = 2, y = 8, x_plus = True, x_minus = True),
        MazeSquare(x = 2, y = 9, y_plus = True),
        MazeSquare(x = 2, y = 10, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 11, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 12, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 13, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 14, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 15, y_plus = True, y_minus = True),
        MazeSquare(x = 2, y = 16, x_plus = True, x_minus = True, y_minus = True),

        MazeSquare(x = 3, y = 1, y_plus = True, x_minus = True),
        MazeSquare(x = 3, y = 2, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 3, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 3, y = 4, y_plus = True, x_minus = True),
        MazeSquare(x = 3, y = 5, x_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 6, y_plus = True),
        MazeSquare(x = 3, y = 7, y_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 8, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 3, y = 9, y_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 10, y_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 11, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 3, y = 12, y_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 13, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 14, x_plus = True, y_minus = True),
        MazeSquare(x = 3, y = 15, x_plus = True),
        MazeSquare(x = 3, y = 16, x_plus = True, x_minus = True),

        MazeSquare(x = 4, y = 1, x_plus = True, y_plus = True),
        MazeSquare(x = 4, y = 2, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 4, y = 3, x_plus = True, y_plus = True, x_minus = True),
        MazeSquare(x = 4, y = 4, x_plus = True, y_minus = True),
        MazeSquare(x = 4, y = 5, x_plus = True, x_minus = True),
        MazeSquare(x = 4, y = 6, y_plus = True),
        MazeSquare(x = 4, y = 7, y_plus = True, y_minus = True),
        MazeSquare(x = 4, y = 8, y_plus = True, y_minus = True),
        MazeSquare(x = 4, y = 9, y_plus = True, y_minus = True),
        MazeSquare(x = 4, y = 10, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 4, y = 11, y_plus = True, y_minus = True),
        MazeSquare(x = 4, y = 12, y_plus = True, y_minus = True),
        MazeSquare(x = 4, y = 13, x_minus = True, y_minus = True),
        MazeSquare(x = 4, y = 14, x_plus = True, x_minus = True),
        MazeSquare(x = 4, y = 15, x_plus = True, x_minus = True),
        MazeSquare(x = 4, y = 16, x_plus = True, x_minus = True),

        MazeSquare(x = 5, y = 1, x_plus = True, x_minus = True),
        MazeSquare(x = 5, y = 2, x_plus = True, x_minus = True),
        MazeSquare(x = 5, y = 3, x_plus = True, x_minus = True),
        MazeSquare(x = 5, y = 4, x_plus = True, x_minus = True),
        MazeSquare(x = 5, y = 5, x_plus = True, x_minus = True),
        MazeSquare(x = 5, y = 6, y_plus = True),
        MazeSquare(x = 5, y = 7, y_plus = True, y_minus = True),
        MazeSquare(x = 5, y = 8, y_plus = True, y_minus = True),
        MazeSquare(x = 5, y = 9, y_plus = True, y_minus = True),
        MazeSquare(x = 5, y = 10, x_minus = True, y_minus = True),
        MazeSquare(x = 5, y = 11, y_plus = True),
        MazeSquare(x = 5, y = 12, y_plus = True, y_minus = True),
        MazeSquare(x = 5, y = 13, y_plus = True, y_minus = True),
        MazeSquare(x = 5, y = 14, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 5, y = 15, y_plus = True, x_minus = True),
        MazeSquare(x = 5, y = 16, x_minus = True, y_minus = True),

        MazeSquare(x = 6, y = 1, x_plus = True, x_minus = True),
        MazeSquare(x = 6, y = 2, x_plus = True, y_plus = True, x_minus = True),
        MazeSquare(x = 6, y = 3, x_minus = True, y_minus = True),
        MazeSquare(x = 6, y = 4, x_plus = True, x_minus = True),
        MazeSquare(x = 6, y = 5, y_plus = True, x_minus = True),
        MazeSquare(x = 6, y = 6, y_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 7, y_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 8, y_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 9, x_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 10, x_plus = True, y_plus = True),
        MazeSquare(x = 6, y = 11, y_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 12, y_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 13, y_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 14, y_plus = True, x_minus = True),
        MazeSquare(x = 6, y = 15, y_plus = True, y_minus = True),
        MazeSquare(x = 6, y = 16, x_plus = True, y_minus = True),

        MazeSquare(x = 7, y = 1, x_plus = True, x_minus = True),
        MazeSquare(x = 7, y = 2, y_plus = True, x_minus = True),
        MazeSquare(x = 7, y = 3, y_plus = True, y_minus = True),
        MazeSquare(x = 7, y = 4, y_plus = True, x_minus = True),
        MazeSquare(x = 7, y = 5, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 7, y = 6, y_plus = True, y_minus = True),
        MazeSquare(x = 7, y = 7, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 7, y = 8, y_plus = True, y_minus = True),
        MazeSquare(x = 7, y = 9, x_minus = True, y_minus = True),
        MazeSquare(x = 7, y = 10, x_plus = True, x_minus = True),
        MazeSquare(x = 7, y = 11, y_plus = True),
        MazeSquare(x = 7, y = 12, y_plus = True, y_minus = True),
        MazeSquare(x = 7, y = 13, y_plus = True, y_minus = True),
        MazeSquare(x = 7, y = 14, y_plus = True, y_minus = True),
        MazeSquare(x = 7, y = 15, y_plus = True, y_minus = True),
        MazeSquare(x = 7, y = 16, x_plus = True, x_minus = True, y_minus = True),

        MazeSquare(x = 8, y = 1, y_plus = True, x_minus = True),
        MazeSquare(x = 8, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 8, y = 3, y_plus = True, y_minus = True),
        MazeSquare(x = 8, y = 4, y_plus = True, y_minus = True),
        MazeSquare(x = 8, y = 5, x_minus = True, y_minus = True),
        MazeSquare(x = 8, y = 6, x_plus = True, y_plus = True),
        MazeSquare(x = 8, y = 7, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 8, y = 8, x_plus = True, y_plus = True, is_finish = True),
        MazeSquare(x = 8, y = 9, x_plus = True, y_minus = True, is_finish = True),
        MazeSquare(x = 8, y = 10, x_plus = True, y_plus = True, x_minus = True),
        MazeSquare(x = 8, y = 11, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 8, y = 12, x_plus = True, y_minus = True),
        MazeSquare(x = 8, y = 13, y_plus = True),
        MazeSquare(x = 8, y = 14, y_plus = True, y_minus = True),
        MazeSquare(x = 8, y = 15, y_plus = True, y_minus = True),
        MazeSquare(x = 8, y = 16, x_plus = True, x_minus = True, y_minus = True),

        MazeSquare(x = 9, y = 1, x_plus = True, y_plus = True),
        MazeSquare(x = 9, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 9, y = 3, y_plus = True, y_minus = True),
        MazeSquare(x = 9, y = 4, y_plus = True, y_minus = True),
        MazeSquare(x = 9, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 9, y = 6, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 9, y = 7, x_plus = True, x_minus = True),
        MazeSquare(x = 9, y = 8, x_plus = True, y_plus = True, x_minus = True, is_finish = True),
        MazeSquare(x = 9, y = 9, x_minus = True, y_minus = True, is_finish = True),
        MazeSquare(x = 9, y = 10, x_plus = True, x_minus = True),
        MazeSquare(x = 9, y = 11, x_plus = True, x_minus = True),
        MazeSquare(x = 9, y = 12, y_plus = True, x_minus = True),
        MazeSquare(x = 9, y = 13, y_plus = True, y_minus = True),
        MazeSquare(x = 9, y = 14, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 9, y = 15, y_minus = True),
        MazeSquare(x = 9, y = 16, x_plus = True, x_minus = True),

        MazeSquare(x = 10, y = 1, x_plus = True, y_plus = True, x_minus = True),
        MazeSquare(x = 10, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 10, y = 3, y_plus = True, y_minus = True),
        MazeSquare(x = 10, y = 4, y_plus = True, y_minus = True),
        MazeSquare(x = 10, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 10, y = 6, x_minus = True, y_minus = True),
        MazeSquare(x = 10, y = 7, x_minus = True),
        MazeSquare(x = 10, y = 8, y_plus = True, x_minus = True),
        MazeSquare(x = 10, y = 9, y_plus = True, y_minus = True),
        MazeSquare(x = 10, y = 10, x_minus = True, y_minus = True),
        MazeSquare(x = 10, y = 11, x_minus = True),
        MazeSquare(x = 10, y = 12, x_plus = True, y_plus = True),
        MazeSquare(x = 10, y = 13, y_plus = True, y_minus = True),
        MazeSquare(x = 10, y = 14, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 10, y = 15, y_plus = True),
        MazeSquare(x = 10, y = 16, x_minus = True, y_minus = True),

        MazeSquare(x = 11, y = 1, x_plus = True, y_plus = True, x_minus = True),
        MazeSquare(x = 11, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 11, y = 3, y_plus = True, y_minus = True),
        MazeSquare(x = 11, y = 4, y_plus = True, y_minus = True),
        MazeSquare(x = 11, y = 5, y_minus = True),
        MazeSquare(x = 11, y = 6, x_plus = True, y_plus = True),
        MazeSquare(x = 11, y = 7, x_plus = True, y_minus = True),
        MazeSquare(x = 11, y = 8, y_plus = True),
        MazeSquare(x = 11, y = 9, y_plus = True, y_minus = True),
        MazeSquare(x = 11, y = 10, y_plus = True, y_minus = True),
        MazeSquare(x = 11, y = 11, x_plus = True, y_minus = True),
        MazeSquare(x = 11, y = 12, x_plus = True, x_minus = True),
        MazeSquare(x = 11, y = 13, y_plus = True),
        MazeSquare(x = 11, y = 14, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 11, y = 15, y_plus = True, y_minus = True),
        MazeSquare(x = 11, y = 16, y_minus = True),

        MazeSquare(x = 12, y = 1, y_plus = True, x_minus = True),
        MazeSquare(x = 12, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 12, y = 3, y_plus = True, y_minus = True),
        MazeSquare(x = 12, y = 4, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 12, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 12, y = 6, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 12, y = 7, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 12, y = 8, y_plus = True),
        MazeSquare(x = 12, y = 9, y_plus = True, y_minus = True),
        MazeSquare(x = 12, y = 10, x_plus = True, y_minus = True),
        MazeSquare(x = 12, y = 11, x_plus = True, x_minus = True),
        MazeSquare(x = 12, y = 12, x_plus = True, x_minus = True),
        MazeSquare(x = 12, y = 13, x_plus = True, y_plus = True),
        MazeSquare(x = 12, y = 14, y_minus = True),
        MazeSquare(x = 12, y = 15, x_plus = True, y_plus = True),
        MazeSquare(x = 12, y = 16, y_minus = True),

        MazeSquare(x = 13, y = 1, y_plus = True),
        MazeSquare(x = 13, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 13, y = 3, y_plus = True, y_minus = True),
        MazeSquare(x = 13, y = 4, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 13, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 13, y = 6, x_plus = True, y_minus = True),
        MazeSquare(x = 13, y = 7, y_plus = True, x_minus = True),
        MazeSquare(x = 13, y = 8, y_plus = True, y_minus = True),
        MazeSquare(x = 13, y = 9, x_plus = True, y_minus = True),
        MazeSquare(x = 13, y = 10, y_plus = True, x_minus = True),
        MazeSquare(x = 13, y = 11, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 13, y = 12, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 13, y = 13, x_plus = True, x_minus = True),
        MazeSquare(x = 13, y = 14, x_plus = True, y_plus = True),
        MazeSquare(x = 13, y = 15, x_minus = True, y_minus = True),
        MazeSquare(x = 13, y = 16, x_plus = True),

        MazeSquare(x = 14, y = 1, y_plus = True),
        MazeSquare(x = 14, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 14, y = 3, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 14, y = 4, y_plus = True, y_minus = True),
        MazeSquare(x = 14, y = 5, x_plus = True, y_minus = True),
        MazeSquare(x = 14, y = 6, x_plus = True, x_minus = True),
        MazeSquare(x = 14, y = 7, x_plus = True, y_plus = True),
        MazeSquare(x = 14, y = 8, y_plus = True, y_minus = True),
        MazeSquare(x = 14, y = 9, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 14, y = 10, y_plus = True, y_minus = True),
        MazeSquare(x = 14, y = 11, y_minus = True),
        MazeSquare(x = 14, y = 12, y_plus = True, x_minus = True),
        MazeSquare(x = 14, y = 13, x_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 14, y = 14, x_plus = True, x_minus = True),
        MazeSquare(x = 14, y = 15, x_plus = True, y_plus = True),
        MazeSquare(x = 14, y = 16, x_plus = True, x_minus = True, y_minus = True),

        MazeSquare(x = 15, y = 1, x_plus = True, y_plus = True),
        MazeSquare(x = 15, y = 2, y_minus = True),
        MazeSquare(x = 15, y = 3, x_plus = True, x_minus = True),
        MazeSquare(x = 15, y = 4, y_plus = True),
        MazeSquare(x = 15, y = 5, x_minus = True, y_minus = True),
        MazeSquare(x = 15, y = 6, x_plus = True, x_minus = True),
        MazeSquare(x = 15, y = 7, y_plus = True, x_minus = True),
        MazeSquare(x = 15, y = 8, x_plus = True, y_plus = True, y_minus = True),
        MazeSquare(x = 15, y = 9, y_plus = True, y_minus = True),
        MazeSquare(x = 15, y = 10, y_plus = True, y_minus = True),
        MazeSquare(x = 15, y = 11, y_plus = True, y_minus = True),
        MazeSquare(x = 15, y = 12, y_minus = True),
        MazeSquare(x = 15, y = 13, x_plus = True, x_minus = True),
        MazeSquare(x = 15, y = 14, x_plus = True, x_minus = True),
        MazeSquare(x = 15, y = 15, x_minus = True),
        MazeSquare(x = 15, y = 16, x_plus = True, x_minus = True),

        MazeSquare(x = 16, y = 1, y_plus = True, x_minus = True),
        MazeSquare(x = 16, y = 2, y_plus = True, y_minus = True),
        MazeSquare(x = 16, y = 3, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 16, y = 4, y_plus = True, y_minus = True),
        MazeSquare(x = 16, y = 5, y_plus = True, y_minus = True),
        MazeSquare(x = 16, y = 6, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 16, y = 7, y_minus = True),
        MazeSquare(x = 16, y = 8, y_plus = True, x_minus = True),
        MazeSquare(x = 16, y = 9, y_plus = True, y_minus = True),
        MazeSquare(x = 16, y = 10, y_plus = True, y_minus = True),
        MazeSquare(x = 16, y = 11, y_plus = True, y_minus = True),
        MazeSquare(x = 16, y = 12, y_plus = True, y_minus = True),
        MazeSquare(x = 16, y = 13, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 16, y = 14, y_plus = True, x_minus = True, y_minus = True),
        MazeSquare(x = 16, y = 15, y_plus = True, y_minus = True),
        MazeSquare(x = 16, y = 16, x_minus = True, y_minus = True)
    ]
    return Maze(_squares)

# maze = create_simple_2_to_2_maze()
# maze = create_simple_3_to_3_maze()
# maze = create_6_to_6_maze()
maze = create_a_real_16_to_16_beast()
simulator_session = SimulatorMazeSolvingSession(maze)
simulator_session.start()